version: "2"

services:

  analytics_api:
    image: edxops/analytics-api-dev:latest
    container_name: analytics_api_testing
    volumes:
      - ..:/edx/app/analytics_api/analytics_api
    command: tail -f /dev/null
    environment:
      ELASTICSEARCH_LEARNERS_HOST: "http://es:9223"
    depends_on:
      - "es"

  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: es
    environment:
      - node.name=es
      - cluster.name=docker-cluster
      - cluster.initial_master_nodes=es
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - http.port=9223
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - "9223:9223"

volumes:
  data01:
    driver: local
